services:
  db:
    image: pgvector/pgvector:pg16
    container_name: capstone_db
    environment:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: capstone1234
      POSTGRES_DB: capstone_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U capstone -d capstone_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
