"""add session_records table

Revision ID: 076b5b1fde2c
Revises: 
Create Date: 2026-05-11 21:16:08.826874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076b5b1fde2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('termination_reason', sa.String(length=50), nullable=True),
    sa.Column('coverage_percent', sa.Float(), nullable=True),
    sa.Column('misconceptions', sa.JSON(), nullable=True),
    sa.Column('session_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_records_document_id'), 'session_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_session_records_id'), 'session_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_records_id'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_document_id'), table_name='session_records')
    op.drop_table('session_records')
    # ### end Alembic commands ###
